FROM alpine:latest

RUN apk update && apk --no-cache add mosquitto

EXPOSE 1883

RUN mkdir -p /mqtt/

COPY config/mosquitto.conf /mqtt/config/mosquitto.conf

RUN mkdir -p /var/lib/mosquitto/

ENTRYPOINT ["/usr/sbin/mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
