// Code generated by mockery v1.0.0. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockActuator is an autogenerated mock type for the Actuator type
type MockActuator struct {
	mock.Mock
}

// GetState provides a mock function with given fields:
func (_m *MockActuator) GetState() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Setup provides a mock function with given fields:
func (_m *MockActuator) Setup() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TurnOff provides a mock function with given fields:
func (_m *MockActuator) TurnOff() {
	_m.Called()
}

// TurnOn provides a mock function with given fields:
func (_m *MockActuator) TurnOn() {
	_m.Called()
}
