// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import time "time"

// MockWaterLevelMeasurer is an autogenerated mock type for the WaterLevelMeasurer type
type MockWaterLevelMeasurer struct {
	mock.Mock
}

// GetWaterLevel provides a mock function with given fields:
func (_m *MockWaterLevelMeasurer) GetWaterLevel() (float32, time.Time) {
	ret := _m.Called()

	var r0 float32
	if rf, ok := ret.Get(0).(func() float32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 time.Time
	if rf, ok := ret.Get(1).(func() time.Time); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	return r0, r1
}

// GetWaterLevelFeed provides a mock function with given fields:
func (_m *MockWaterLevelMeasurer) GetWaterLevelFeed() float32 {
	ret := _m.Called()

	var r0 float32
	if rf, ok := ret.Get(0).(func() float32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float32)
	}

	return r0
}

// SetWaterLevel provides a mock function with given fields: _a0
func (_m *MockWaterLevelMeasurer) SetWaterLevel(_a0 float32) {
	_m.Called(_a0)
}
