// Code generated by mockery v1.0.0. DO NOT EDIT.

package sensors

import mock "github.com/stretchr/testify/mock"

// mockI2cDevice is an autogenerated mock type for the i2cDevice type
type mockI2cDevice struct {
	mock.Mock
}

// ReadRegU16BE provides a mock function with given fields: reg
func (_m *mockI2cDevice) ReadRegU16BE(reg byte) (uint16, error) {
	ret := _m.Called(reg)

	var r0 uint16
	if rf, ok := ret.Get(0).(func(byte) uint16); ok {
		r0 = rf(reg)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(byte) error); ok {
		r1 = rf(reg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
