// Code generated by mockery v1.0.0. DO NOT EDIT.

package sensors

import mock "github.com/stretchr/testify/mock"

// MockSensor is an autogenerated mock type for the Sensor type
type MockSensor struct {
	mock.Mock
}

// GetState provides a mock function with given fields:
func (_m *MockSensor) GetState() (float32, error) {
	ret := _m.Called()

	var r0 float32
	if rf, ok := ret.Get(0).(func() float32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetupDevice provides a mock function with given fields:
func (_m *MockSensor) SetupDevice() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
